"""initial_schema_with_integer_ids

Revision ID: c7b9c5777129
Revises: 
Create Date: 2025-06-07 15:23:54.401632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID # For JobPost model


# revision identifiers, used by Alembic.
revision: str = 'c7b9c5777129'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create users table
    op.create_table('users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('mobile_number', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.Column('is_admin', sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), onupdate=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_mobile_number'), 'users', ['mobile_number'], unique=True)

    # Create otps table
    op.create_table('otps',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('mobile_number', sa.String(), nullable=True),
        sa.Column('otp_code', sa.String(), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('used', sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otps_email'), 'otps', ['email'], unique=False)
    op.create_index(op.f('ix_otps_id'), 'otps', ['id'], unique=False)
    op.create_index(op.f('ix_otps_mobile_number'), 'otps', ['mobile_number'], unique=False)

    # Create job_posts table
    op.create_table('job_posts',
        sa.Column('id', UUID(as_uuid=True), nullable=False),
        sa.Column('PostingDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('RoleName', sa.String(), nullable=True),
        sa.Column('DepartmentName', sa.String(), nullable=True),
        sa.Column('Location', sa.String(), nullable=True),
        sa.Column('CompanyName', sa.String(), nullable=True),
        sa.Column('ContactEmail', sa.String(), nullable=True),
        sa.Column('ApplicationLink', sa.String(), nullable=True),
        sa.Column('JobDescription', sa.Text(), nullable=True),
        sa.Column('ReferralStatus', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), onupdate=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_posts_id'), 'job_posts', ['id'], unique=False)
    op.create_index(op.f('ix_job_posts_RoleName'), 'job_posts', ['RoleName'], unique=False)
    op.create_index(op.f('ix_job_posts_Location'), 'job_posts', ['Location'], unique=False)
    op.create_index(op.f('ix_job_posts_CompanyName'), 'job_posts', ['CompanyName'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_posts_CompanyName'), table_name='job_posts')
    op.drop_index(op.f('ix_job_posts_Location'), table_name='job_posts')
    op.drop_index(op.f('ix_job_posts_RoleName'), table_name='job_posts')
    op.drop_index(op.f('ix_job_posts_id'), table_name='job_posts')
    op.drop_table('job_posts')

    op.drop_index(op.f('ix_otps_mobile_number'), table_name='otps')
    op.drop_index(op.f('ix_otps_id'), table_name='otps')
    op.drop_index(op.f('ix_otps_email'), table_name='otps')
    op.drop_table('otps')

    op.drop_index(op.f('ix_users_mobile_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
